# Generated by Django 6.1.1 on 2026-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('solicitante', models.CharField(max_length=40)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('média', 'Média'), ('baixa', 'Baixa')], max_length=13)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em andamento', 'Em andamento'), ('fechado', 'Fechado')], max_length=12)),
            ],
        ),
    ]
